vault_file: "vault.txt"
vector_store_path: "./chroma_db_notebook"
embed_model: "nomic-embed-text:latest"
ollama_model: "llama3.1:8b"
top_k: 5
system_message: |
  You are an expert AI assistant. 
  Use the provided context to answer the user's questions accurately and concisely.
  If the context does not contain the answer, state that you don't know.
